version: "3.8"

services:
  db:
    image: "postgres:14-alpine"
    volumes:
      - "${HOME}/postgres-data/:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=<db password>"
    networks:
      - app

  app:
    image: "sconaway/musa"
    environment:
      - "DATABASE_URL=postgresql://postgres:<url-encoded db password>@db:5432/postgres"
      - "SLACK_CLIENT_ID=<slack id>"
      - "SLACK_CLIENT_SECRET=<slack secret>"
      - "SPOTIFY_CLIENT_ID=<spotify id>"
      - "SPOTIFY_CLIENT_SECRET=<spotify secret>"
      - "HOST=https://<final base url, no slash at end>"
    networks:
      - app
    depends_on:
      - db
    ports:
      - "3000:3000" # or expose however you want

networks:
  app:
